- server/9in/build.gradle
- server/9in/src/main/java/com/inProject/in/Application.java
- server/9in/src/main/java/com/inProject/in/Global/BaseEntity.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/UserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/entity/User.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/UserRepository.java
- server/9in/src/main/resources/application.properties
user entity, Dto, repository 세팅
mariaDB 설정. gradle, properties
BaseEntity 세팅. 엔티티 생성, 수정 시간 항시 체크 가능하도록.
> Feat : Add user entity, config

- server/9in/build.gradle
- server/9in/src/main/java/com/inProject/in/Global/BaseEntity.java
- server/9in/src/main/java/com/inProject/in/domain/Post/entity/Post.java
- server/9in/src/main/java/com/inProject/in/domain/Post/repository/CustomPostRepository.java
- server/9in/src/main/java/com/inProject/in/domain/Post/repository/Impl/CustomPostRepositoryImpl.java
- server/9in/src/main/java/com/inProject/in/domain/Post/service/PostService.java
- server/9in/src/main/java/com/inProject/in/domain/Post/service/impl/PostServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/UserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/Impl/CustomUserRepositoryImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/service/Impl/UserServiceImpl.java
- server/9in/src/test/java/com/inProject/in/domain/Post/repository/Impl/CustomPostRepositoryImplTest.java
페이징 적용한 게시글 가져오는 쿼리 추가
아이디 검색해서 게시글 찾는 쿼리 추가
두 쿼리 테스트 코드 추가
유효성 검사 코드 추가
querydsl-core 버젼 4.4.0 -> 5.0.0
baseentity에 getter추가.
> Feat : Add Post Repository querydsl

- front/src/ components/header/Header.jsx
- front/src/pages/AddPost.jsx
> Feat: add AddPost page Layout

- front/src/pages/Join/Join.jsx
- front/src/pages/Join/Join.module.css
Design: Join page Layout & CSS
> Design: Join page Layout & CSS

- front/src/pages/Join/Join.jsx
> Feat: add user Join

- front/src/index.js
- front/src/pages/Join/Join.jsx
- front/src/pages/Join/Join.module.css
- front/src/pages/Join/JoinSuccess.jsx
- front/src/pages/Join/JoinSuccess.module.css
Design: JoinSuccess Page Layout & CSS
> Design: JoinSuccess Page Layout & CSS

- front/src/pages/AddPost.jsx
- front/src/pages/Join/Join.jsx
Fix: fix post API data (AddPost, Join)
> Fix: fix post API data (AddPost, Join)

- front/src/ components/header/Logo.jsx
- front/src/index.js
- front/src/pages/AddPost.jsx
- front/src/pages/Join/Project.jsx
- front/src/pages/Project/Project.module.css
- front/src/pages/Project/ProjectPage.jsx
- front/src/pages/Study/Study.module.css
Design: carouseImage & media query  project, study page
> Design: carouseImage & media query  project, study page

- front/src/index.js
- front/src/pages/HomeView.jsx
- front/src/pages/ProfileView.jsx
- front/src/pages/RecruitStatusView.jsx
Style: React component integrate style
> Style: React component integrate style

- front/src/pages/AddPostView.jsx
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/Login/LoginView.module.css
> Feat: add join navigate

- front/src/ components/Post.jsx
- front/src/pages/HomeView.jsx
- front/src/pages/Join/JoinView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
Fix: GET postList api명세서에 맞게 수정
> Fix: GET postList api명세서에 맞게 수정

- front/src/pages/Join/JoinView.jsx
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/Login/LoginView.module.css
Feat: add POST API LoginView page
> Feat: add POST API LoginView page

- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/Login/LoginView.module.css
Design: add styled-component Login page
> Design: add styled-component Login page

- front/src/pages/AddPostView.jsx
- front/src/pages/User/Login/LoginView.jsx
> Feat: store user token

- front/src/index.js
- front/src/pages/AddPostView.jsx
- front/src/pages/HomeView.jsx
Fix: AddPostView POST API & Feat: add postDetail navigate
> Fix: AddPostView POST API & Feat: add postDetail navigate

- front/src/pages/PostDetailView.jsx
Feat: add GET API postDetail & Design: add CSS postDetail
> Feat: add GET API postDetail & Design: add CSS postDetail

- front/src/ components/context/AuthContext.jsx
- front/src/ components/header/Header.jsx
- front/src/App.js
- front/src/pages/User/Login/LoginView.jsx
Feat: add useAuth & add login UI
> Feat: add useAuth & add login UI

- front/src/pages/Project/ProjectView.jsx
- front/src/pages/RecruitStatusView.jsx
- front/src/pages/Study/StudyView.jsx
- front/src/pages/User/MyPage/MyPageView.jsx
Feat: add GET postList RecruitView & add navigate
> Feat: add GET postList RecruitView & add navigate

- server/9in/src/main/java/com/inProject/in/domain/Profile/controller/ProfileController.java
> Feat : add profile controller method

- front/src/ components/Mypage/MypageEtc.jsx
- front/src/ components/Post.jsx
- front/src/ components/hooks/getPostList.jsx
- front/src/index.js
- front/src/pages/HomeView.jsx
- front/src/pages/PostDetailView.jsx
- front/src/pages/User/RecruitStatusView.jsx
Refactor: PostView.jsx (add useFetchData)
> Refactor: PostView.jsx (add useFetchData)

- front/src/ components/context/AuthContext.jsx
- front/src/pages/AddPostView.jsx
- front/src/pages/Join/JoinSuccessView.jsx
- front/src/pages/Join/JoinView.jsx
- front/src/pages/ModifyPostView.jsx
Fix: modifyPostView, AddPostView POST API period data & fix period type
> Fix: modifyPostView, AddPostView POST API period data & fix period type

- front/src/ components/Mypage/MypageModal.jsx
- front/src/pages/ModifyPostView.jsx
- front/src/pages/User/RecruitStatusView.jsx
Feat: add Delete Modal (Delete Post)
> Feat: add Delete Modal (Delete Post)

- front/src/ components/context/AuthContext.jsx
- front/src/pages/AddPostView.jsx
- front/src/pages/ModifyPostView.jsx
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/RecruitStatusView.jsx
Feat: add refresh Token Logic (board post, delete, modify)
> Feat: add refresh Token Logic (board post, delete, modify)

- front/src/ components/context/AuthContext.jsx
- front/src/pages/AddPostView.jsx
- front/src/pages/ModifyPostView.jsx
- front/src/pages/PostDetailView.jsx
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/RecruitStatusView.jsx
Feat: add board apply API (application)
> Feat: add board apply API (application)

- server/9in/src/main/java/com/inProject/in/domain/Board/Dto/ResponseBoardDto.java
- server/9in/src/main/java/com/inProject/in/domain/Board/Dto/ResponseBoardListDto.java
- server/9in/src/main/java/com/inProject/in/domain/Board/entity/Board.java
- server/9in/src/main/java/com/inProject/in/domain/Board/service/impl/BoardServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Application/controller/ApplicationController.java
- server/9in/src/main/java/com/inProject/in/domain/MToNRelation/ApplicantBoardRelation/entity/ApplicantBoardRelation.java
- server/9in/src/main/java/com/inProject/in/domain/MToNRelation/ApplicantRoleRelation/entity/ApplicantRoleRelation.java
- server/9in/src/main/java/com/inProject/in/domain/MToNRelation/ClipBoardRelation/entity/ClipBoardRelation.java
- server/9in/src/main/java/com/inProject/in/domain/MToNRelation/RoleBoardRelation/entity/RoleBoardRelation.java
- server/9in/src/main/java/com/inProject/in/domain/MToNRelation/TagBoardRelation/entity/TagBoardRelation.java
- server/9in/src/main/java/com/inProject/in/domain/Profile/entity/Education.java
- server/9in/src/main/java/com/inProject/in/domain/Profile/entity/Job_ex.java
- server/9in/src/main/java/com/inProject/in/domain/Profile/entity/MyInfo.java
- server/9in/src/main/java/com/inProject/in/domain/Profile/entity/Project_skill.java
- server/9in/src/main/java/com/inProject/in/domain/SkillTag/Dto/ResponseSkillTagDto.java
- server/9in/src/main/java/com/inProject/in/domain/SkillTag/controller/SkillTagController.java
- server/9in/src/main/java/com/inProject/in/domain/SkillTag/service/Impl/SkillTagServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/SkillTag/service/SkillTagService.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/ResponseInfoInBoardDto.java
지연로딩만 사용하도록 변경
response에 생성자에 relation을 이용해 list에 값을 추가하는 로직을 service로 다 옮김.
> Feat : modify response constructor, fetch properfy.

- server/9in/src/main/java/com/inProject/in/config/security/SecurityConfig.java
- server/9in/src/main/java/com/inProject/in/domain/Board/Dto/RequestCreateBoardDto.java
- server/9in/src/main/java/com/inProject/in/domain/Board/controller/BoardController.java
- server/9in/src/main/java/com/inProject/in/domain/Board/entity/Board.java
- server/9in/src/main/java/com/inProject/in/domain/Board/repository/Impl/CustomBoardRepositoryImpl.java
- server/9in/src/main/java/com/inProject/in/domain/Board/service/impl/BoardServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Application/controller/ApplicationController.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sign/Dto/RequestSignInDto.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sign/Dto/RequestSignUpDto.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sign/controller/SignController.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sign/service/Impl/SignServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/controller/SseController.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/repository/SseRepository.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/service/SseService.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/service/impl/SseServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/RequestUserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/ResponseUserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/Dto/UpdateUserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/controller/UserController.java
- server/9in/src/main/java/com/inProject/in/domain/User/entity/User.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/CustomUserRepository.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/Impl/CustomUserRepositoryImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/UserRepository.java
- server/9in/src/main/java/com/inProject/in/domain/User/service/Impl/UserServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/service/UserService.java
- server/9in/src/test/java/com/inProject/in/domain/Board/service/impl/BoardServiceImplTest.java
이전 풀리퀘스트에서 보안이슈있는 커밋 제외하고 다시 올립니다
> FEAT : Apply sse func

- front/src/api/user.js
- front/src/pages/AddPostView.jsx
- front/src/pages/ModifyPostView.jsx
- front/src/pages/User/RecruitStatusView.jsx
Refactor: refactoring get refresh token & retry
> Refactor: refactoring get refresh token & retry

- front/src/ components/context/AuthContext.jsx
> Feat: add logOut API

- front/src/pages/User/IDFound/IDfoundView.jsx
- front/src/pages/User/IDFound/IDfoundView.module.css
> Feat: findID API & Design: change Layout & add CSS - IDfoundView

- front/src/pages/User/PWfound/PWfound.module.css
- front/src/pages/User/PWfound/PWfoundView.jsx
비밀번호 변경화면 API추가, 레이아웃 및 스타일링 변경
> Feat: add findPw API & Design: change Layout, css in PWfoundView

- front/src/pages/User/PWChange/PWChange.module.css
- front/src/pages/User/PWChange/PWChangeView.jsx
비밀번호 변경 로직 구현 -> 기존 비밀번호 찾기 API 추가요청 & 아이디확인 및 기존 비밀번호 체크 추가 구현 해야함
> Feat: add change PW API & change Layout in PWChangeView

- front/src/ components/Post.module.css
- front/src/pages/PostDetailView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
- front/src/pages/User/ClipView.jsx
> Feat: add post content

- front/src/pages/User/IDFound/IDfoundView.jsx
> Feat: add valid API & change Layout in IDFoundView

- front/src/pages/User/IDFound/IDfoundView.jsx
아이디찾기 validation API 추가 및 API 수정사항 반영
> Feat: add validation API (IDFoundView)

- front/src/modules/auth.js
- front/src/modules/user.js
> Feat: add user.js redux module

- server/9in/docker-compose.yml
docker-compose.yml에서 임의의 값들로 들어간 부분들 수정
> Fix : modify docker-compose.yml

- .github/workflows/gradle.yml
github action 적용. main에 pull request발생 시 동작한다.
> Feat : Create gradle.yml

- .github/workflows/gradle.yml
cd로 9in으로 이동하지 않아 한 번에 cd랑 gradlw/build 진행.
> Fix : error gradle.yml

- .github/workflows/gradle.yml
> Fix : move build  gradle.yml

- .github/workflows/gradle.yml
> Fix: Update wrong typing

- .github/workflows/gradle.yml
> Fix: step run cd

- front/src/pages/User/PWChange/PWChangeView.jsx
> Fix: change layout & refactor PWChangeView

- front/src/ components/tag/Tag.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Project/ProjectView.module.css
- front/src/pages/Study/StudyView.jsx
- front/src/pages/Study/StudyView.module.css
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/PWfound/PWfoundView.jsx
Refactor: change CSS proejectView, StudyView (add styled component)
> Refactor: change CSS proejectView, StudyView (add styled component)

- .github/workflows/gradle.yml
다른 브랜치에 push발생 시 ci/cd 하지 않도록 함.
appleboy로 ssh 접속하는 부분 제외.
> Fix: exclude appleboy/ssh

- .github/workflows/gradle.yml
appleboy 다시 적용. 이전에는 workflow 성공해도 deploy가 동작하지 않음.
> Fix: accept appleboy

- front/src/pages/HomeView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
> Design: add CSS in pagination

- .github/workflows/gradle.yml
job을 두 개로 분리.
deploy단계에서 docker-compose.yml복사 추가.
> Fix: devide build, deploy

- .github/workflows/gradle.yml
> Fix: permission

- .github/workflows/gradle.yml
> Fix : target path update

- server/9in/docker-compose.yml
> Fix: modify container name

- .github/workflows/gradle.yml
> Fix : modify source path

- front/src/pages/Join/JoinView.jsx
- front/src/pages/Join/JoinView.module.css
> Feat: add valid API in JoinView

- front/src/ components/header/Footer.jsx
- front/src/pages/HomeView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
> Feat: boarList pagination

- front/src/pages/PostDetailView.jsx
* 게시글 api 버그 수정
* creatAt (게시날짜) 데이터 추가
> 게시글 api버그수정

- front/src/pages/PostDetailView.jsx
게시글 상세페이지 css 수정
* px -> rem
* margin추가 및 값 변경
> 게시글 상세페이지 css 수정

- front/src/api/sse.js
- front/src/pages/PostDetailView.jsx
> Feat: add sse eventSource

- front/package.json
- front/src/DockerFile
- front/src/api/sse.js
- front/src/pages/PostDetailView.jsx
- front/src/pages/User/Login/LoginView.jsx
> 도커파일 추가 및 build dev, local 스크립트 추가

- server/9in/src/main/java/com/inProject/in/domain/User/Dto/ResponseUserDto.java
- server/9in/src/main/java/com/inProject/in/domain/User/controller/UserController.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/Impl/CustomUserRepositoryImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/repository/UserRepository.java
- server/9in/src/main/java/com/inProject/in/domain/User/service/Impl/UserServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/User/service/UserService.java
> Feat : add get user List

- server/9in/src/main/java/com/inProject/in/domain/Board/service/impl/BoardServiceImpl.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/controller/SseController.java
- server/9in/src/main/java/com/inProject/in/domain/CommonLogic/Sse/service/impl/SseServiceImpl.java
커넥션 누수 발생
osiv 옵션 false로 지정
getboards부분 수정. transaction으로 적용
ssecontroller 미디어 타입 추가
emitter완료 시 emitter삭제
> Fix : connection leaked

- front/src/App.css
- front/src/pages/PostDetailView.jsx
> 게시글 상세페이지 댓글 레이아웃 추가

- front/Dockerfile
- front/src/pages/Home.module.css
- front/src/pages/PostDetailView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Project/ProjectView.module.css
- front/src/pages/Study/StudyView.jsx
- front/src/pages/Study/StudyView.module.css
> 도커파일 수정 및 게시글 리스트 스타일 변경

- front/src/api/instance.js
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
* 스터디 게시물 리스트 제목 검색기능 추가
* 프로젝트 게시물 리스트 제목 검색기능 추가
> 게시글 리스트 제목 검색기능 추가

- front/src/pages/AddPostView.jsx
- front/src/pages/PostDetailView.jsx
* 작성자 지원경우 예외처리
* 댓글 scroll 추가
> 지원하기 예외처리 

- front/src/ components/header/Header.jsx
- front/src/api/instance.js
- front/src/pages/HomeView.jsx
- front/src/pages/PostDetailView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* createAxiosInstance params 형식 추가
* 모집현황페이지 게시글 리스트 버그 수정 (createAxiosInstance로 마이그레이션)
> axiosInstance 형식 변경 및 모집현황 페이지 api 버그 수정

- front/src/ components/header/Header.jsx
- front/src/api/sse.js
- front/src/modules/alarm.js
- front/src/modules/index.js
- front/src/pages/HomeView.jsx
- front/src/pages/PostDetailView.jsx
- front/src/pages/Project/ProjectView.jsx
- front/src/pages/Study/StudyView.jsx
- front/src/pages/User/Login/LoginView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* 기존connect api -> login후 호출하도록 변경
* 로그인 후 notify api호출
* alarm.js에 알람리스트 전역 데이터 관리
* header에 알람이 있을 경우 반영
* 모집현황페이지 알람리스트 동적 데이터 반영
> SSE notify API 호출 및 전역 데이터 처리

- front/src/pages/PostDetailView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* 지원하기 후 notify post api추가
* 알람 데이터 동적 처리
> 알람 api 추가 및 데이터 반영

- front/src/pages/PostDetailView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* 모집화면 프로젝트, 스터디 수 추가
* 게시글 내용 추가
* 게시글 작성자 이름 추가
> UI 수정사항 반영 

- front/src/ components/header/Header.jsx
- front/src/pages/PostDetailView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* 게시글 상세 페이지 댓글 텍스트 추가
* 헤더 hover시 유저 추가
> 테스트 수정사항 수정

- front/src/pages/PostDetailView.jsx
- front/src/pages/User/RecruitStatusView.jsx
* 사용자 게시글 신청 데이터 수정
* 알람 거절하기 api추가
> 신청 수정 & 거절하기 api추가
